### PR TITLE
chore: Upgrade to Angular version 8

### LINKED ISSUE #48: Update to Angular 8

### PR DESCRIPTION
**Pull request by flavens**
Upgrade the project to Angular 8.

resolve #48 

N.B.: The Knora-UI modules from the branch wip/update-to-angular8 are needed to review this PR. Should be published on NPM.

### CODE REVIEW

**Comment by flavens** [comment]
[Knora-ui/Kuirl/Knora-ui-playground: Update to Angular 8](https://trello.com/c/5Ms8ppBQ/106-knora-ui-kuirl-knora-ui-playground-update-to-angular-8)

**Comment by flavens** [comment]
@kilchenmann I think I will need your help to resolve conflicts without any mistakes, whenever you have time..

**Comment by kilchenmann** [comment]
@flavens Do we have to import the material modules in a new way? 

Screenshot 2019-08-29 at 09 13 06

**Comment by flavens** [comment]
@kilchenmann yes now we have to import each Mat module individually: `@angular/material/xx-mat-xx`

**Comment by kilchenmann** [comment]
> @kilchenmann yes now we have to import each Mat module individually: `@angular/material/xx-mat-xx`

Where did you saw it? I was looking for this "new" import? On the material.angular.io page it was always in the API section of each module, to import like this. But the main @angular/material module still have an index with all modules. Or doesn't it work anymore this way?

**Comment by flavens** [comment]
@kilchenmann I followed the recommendations of the Angular Update Guide

**Comment by kilchenmann** [comment]
@flavens I think we can merge it?

**Pull request merged**
