### PR TITLE
feat: Better password form handling

### LINKED ISSUE #43: Button "next" still displayed
**Describe the bug**
Change (not own) user's password has an issue at the end of the form. 
There's still "Next" button.

**To Reproduce**

1. Go to 'http://localhost:4200/system/users'
2. Click on 'Change user's password'
3. Fill in the form until the end
4. See error at the bottom right of the dialog box

**Expected behavior**
No button

**Screenshots**
N.A.

**Additional context**
N.A.

### PR DESCRIPTION
**Pull request by kilchenmann**
We optimized the workflow when changing not-own password. Resolves #43 
And we added a second password field to confirm password to avoid misstyping.

The new password-form component is used to:
- create new password in user-form
- update own password in account view, but also in users list in system view
- update other user password in users list in system view

### CODE REVIEW

**Comment by flavens** [comment]
@kilchenmann I would suggest to highlight the Confirm password input field in red when there is a mismatch. And change the message "You are entering **sudo** mode." in the edit user's password form. Not everyone knows what "sudo mode" means..

**Comment by flavens** [comment]
This is what I get when I want to create a new user in sytem > All users > Create new (http://localhost:4200/system/users):

Screenshot 2019-08-26 at 08 49 23

**Comment by kilchenmann** [comment]
> And change the message "You are entering sudo mode." in the edit user's password form. Not everyone knows what "sudo mode" means..
I took the sentence  "You are entering sudo mode." from Github. Only system admin will see this and they should know what sudo means. But do you have a better sentence?

**Comment by kilchenmann** [comment]
I will have a look on the error you get. I try with the [latest Knora release](https://github.com/dhlab-basel/Knora/releases/tag/v8.1.0).

**Comment by kilchenmann** [comment]
@flavens: It should work now

**Pull request merged**
