### PR TITLE
feat: system view > manage user's project membership

### LINKED ISSUE #55: Add user to project
**Is your feature request related to a problem? Please describe.**
In users list in system view, we prepared a menu item to add user to a project directly. This feature is not yet implemented.

**Describe the solution you'd like**
Extend this feature with a list of projects, where the user is already member of and with the possibility to remove user from a specific project. Better menu label: "Manage project membership"

**Describe alternatives you've considered**
N.A.

**Additional context**
N.A.

### PR DESCRIPTION
**Pull request by kilchenmann**
There was the idea to add a user to a project from system view "list of users". This PR implements this missing feature as "Manage project membership" for each user. Resolves #55

### CODE REVIEW

**Comment by flavens** [comment]
Great form! Looks very nice! 
I have just 2 little things:
 
1. I have noticed that the drop-down menu opens at the top of the dialog box when there are 2 or more selected projects in the list (when there is only one project, the menu opens in front of the menu field):
Screenshot 2019-08-26 at 10 46 48

2. I have added my user (myself) as a collaborator and admin to the BEOL project (as a test). But when I open the membership dialog box in system>all users right after, the project BEOL does not appear in the list. I have to refresh the page manually.

**Comment by kilchenmann** [comment]
> I have noticed that the drop-down menu opens at the top of the dialog box when there are 2 or more selected projects in the list (when there is only one project, the menu opens in front of the menu field):

hm...strange. It never happened to me. I will test it again, as soon my local knora installation works again.

> I have added my user (myself) as a collaborator and admin to the BEOL project (as a test). But when I open the membership dialog box in system>all users right after, the project BEOL does not appear in the list. I have to refresh the page manually.

Then it's a issue with the cache service. I will fix it

**Comment by kilchenmann** [comment]
Oh...I saw that I forgot to exclude the knora default projects. I will fix that too

**Comment by kilchenmann** [comment]
@flavens It should work now

**Comment by flavens** [comment]
@kilchenmann I still have the same project with the cache. After adding a user from http://localhost:4200/system/projects, the list in http://localhost:4200/system/users is not up-to-date. It updates after a manual reload of the page.

**Comment by kilchenmann** [comment]
I can't reproduce the mentioned issue. Did you used browser's "previous page"-button? 
I added me to the Webern project and switched to system/users and clicked on "manage project membership" and the Webern project was listed there. I did the same in reverse: In system/users I added me to the BEOL and switched to the BEOL collaboration page and I was listed there as well.
But it's true, when I use the "previous page"-button it doesn't refresh the page. This is an issue in general. I will try to fix in a quick way: Update project cache in the membership component.

**Comment by flavens** [comment]
@kilchenmann Another little thing: when I delete a project from the list and I want to add it again without closing/reopening the dialog box, the list is not up-to-date. So if you delete the wrong project, you have to close/open the dialog or reload the page.. Cache again I suppose.

**Comment by kilchenmann** [comment]
> when I delete a project from the list and I want to add it again without closing/reopening the dialog box, the list is not up-to-date. 

You mean in the Membership-thing?

**Comment by flavens** [comment]
@kilchenmann yes in the Membership dialog box

**Comment by kilchenmann** [comment]
@flavens I tried to fix the mentioned issue about updating cache. Would you have a look on it again

**Comment by flavens** [comment]
@kilchenmann LGTM

**Comment by kilchenmann** [comment]
@flavens Thanks

**Pull request merged**
