### PR TITLE
feat: Simple list creator

### PR DESCRIPTION
**Pull request by kilchenmann**
In this PR we implemented a simple list creator. A project admin can create new list and add nodes.
Edit nodes, delete nodes or the whole list and change sort order is not yet supported.

### CODE REVIEW

**Comment by kilchenmann** [comment]
TODO: we have to publish a new version of knora-ui modules to get the tests running. There's an open PR [#270](https://github.com/dhlab-basel/Knora-ui/pull/270)

**Comment by flavens** [comment]
@kilchenmann the Edit list form in the dialog box is not responsive > I suggest to fix the width or hide this section on phone format

**Comment by kilchenmann** [comment]
@flavens we should hide the list on phone view

**Comment by flavens** [comment]
I got a weird error while running Kuirl on my computer:
Screen Shot 2019-08-19 at 16 10 42

It can be fixed like this:
`@media (max-width: 768px) and (min-width: 576px) {
        ...
}`

**Comment by kilchenmann** [comment]
@flavens this can be reviewed now

**Pull request merged**
